# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://esaki.tk/"
DefaultContentLanguage  = "en"
title                   = "Esaki Official Website"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "A Blog and a Project Idea handbook."
    author              = "Miguel Freytes"
    favicon             = true
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Home"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Esaki"
    paragraph             = "A Blog and a Project Idea handbook by Miguel Freytes."
    rssIntro              = false
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/esaki.png"
      shape               = "circle"
      width               = ""
      alt                 = "Esaki Diode"

  [params.sidebar]
    about               = "The purpose of this site is to help electronics enthusiasts to learn more about this wonderful world."
    postAmount          = 3
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "Projects"
    identifier        = "projects"
    url               = "/projects/"
    pre               = "<i class='fas fa-puzzle-piece'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1



  [Languages.es]
    
    LanguageCode        = "es"
    LanguageName        = "Español"
    weight              = 2
    title = "Esaki Página Oficial"

    [Languages.es.params]
      enableCDN             = false
      cssFiles              = ["default"]
      jsFiles               = ["default"]
      highlightjs           = true
      highlightjsTheme      = ""
      highlightjsLang       = []
      viewMorePostsLink     = "/blog/"
      readingTime           = true
      imageStretch          = ""
      removeBlur            = false
      socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
      hideEmptyStats        = false

      [Languages.es.params.meta]
      author              = "Miguel Freytes"
      favicon             = false
      svg                 = true
      faviconVersion      = "1"
      msColor             = "#ffffff"
      iOSColor            = "#ffffff"
      description = "Blog y Catálogo de proyectos de Electrónica por Miguel Freytes"

      [Languages.es.params.header]

      navbarTitle = "Inicio"
      dynamicTitles       = true
      searchMenu          = true
      shareMenu           = true
      languageMenu        = true
      
      [Languages.es.params.intro]
      rssIntro              = false
      socialIntro           = true
      hideWhenSingleColumn  = false
      alwaysOnHomepage      = false
      paragraph = "Blog y Catálogo de proyectos de Electrónica por Miguel Freytes"

        [Languages.es.params.intro.pic]
        src                 = "img/main/esaki.png"
        shape               = "circle"
        width               = ""
        alt                 = "Diodo Esaki"

      [Languages.es.params.sidebar]
      about               = "El propósito de este sitio es ayudar a los entusiastas de la electrónica a conocer más acerca de este maravilloso mundo"
      postAmount          = 3
      categories          = true
      categoriesByCount   = true

    [Languages.es.menu]

      [[Languages.es.menu.main]]
        name              = "Inicio"
        identifier        = "inicio"
        url               = "/"
        pre               = "<i class='fa fa-home'></i>"
        weight            = 1

      [[Languages.es.menu.main]]
        name              = "Proyectos"
        identifier        = "proyectos"
        url               = "/projects/"
        pre               = "<i class='fas fa-puzzle-piece'></i>"
        weight            = 2

      [[Languages.es.menu.main]]
        name              = "Blog"
        identifier        = "blog"
        url               = "/blog/"
        pre               = "<i class='far fa-newspaper'></i>"
        weight            = 3

      [[Languages.es.menu.main]]
        name              = "Categorías"
        identifier        = "categorías"
        url               = "/categories/"
        pre               = "<i class='fas fa-sitemap'></i>"
        weight            = 5

      [[Languages.es.menu.main]]
        name              = "Contacto"
        identifier        = "contacto"
        url               = "/contact/"
        pre               = "<i class='far fa-envelope'></i>"
        weight            = 6
    

  
[social]
  # Coding Communities
  github                = "mianfremo"

  instagram             = "miguel.freytes"

  twitter               = "freytesssss"

  # Email
  email                 = "miguelfreytes09@gmail.com"
